'use client'
/**
 * @fileOverview Terms of Service page for Cooking Lab.
 */
export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-20">

        <div className="mb-12">
          <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground mb-4">
            Legal
          </p>
          <h1 className="text-4xl font-bold tracking-tight text-foreground mb-4">
            Terms of Service
          </h1>
          <p className="text-muted-foreground">
            Last updated: March 2026
          </p>
        </div>

        <div className="space-y-10 text-sm text-muted-foreground leading-relaxed">

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              1. Acceptance of Terms
            </h2>
            <p>
              By using Cooking Lab you agree to these 
              Terms of Service. If you do not agree 
              please do not use the platform.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              2. Use of Service
            </h2>
            <p>
              Cooking Lab is a free AI powered recipe 
              generation platform. You may use it for 
              personal and non-commercial purposes.
            </p>
            <p>
              You must not misuse the platform — 
              including attempting to generate harmful 
              content or overloading the AI system 
              with excessive requests.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              3. User Accounts
            </h2>
            <p>
              You are responsible for maintaining the 
              security of your account. Please use a 
              strong password and do not share your 
              login credentials with anyone.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              4. Community Content
            </h2>
            <p>
              When you share recipes to the Explore 
              community they become visible to all 
              users. Please only share appropriate 
              food related content.
            </p>
            <p>
              You retain ownership of recipes you 
              generate. By sharing to the community 
              you grant other users the right to view 
              and save your recipes.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              5. AI Generated Content
            </h2>
            <p>
              Recipes are generated by AI and may not 
              always be perfectly accurate. Always use 
              your own judgment when following any 
              recipe — especially regarding allergens, 
              cooking temperatures and food safety.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              6. Availability
            </h2>
            <p>
              Cooking Lab is provided as is. We do not 
              guarantee uninterrupted availability of 
              the service. This is a student project 
              and may be updated or modified at any time.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              7. Changes to Terms
            </h2>
            <p>
              We may update these terms from time to 
              time. Continued use of Cooking Lab after 
              changes means you accept the updated terms.
            </p>
          </section>

        </div>
      </div>
    </div>
  )
}
